### ISSUE TITLE
Project export leads to a warning

### ISSUE THREAD

**Issue by aad4** [joomleague/JoomLeague#69]
When exporting a project, this leads to a PHP Warning:
mb_strtolower() expects parameter 1 to be string, array given in $/libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 114,
due to visiting next URL
  http://$/administrator/index.php?option=com_joomleague&view=jlxmlexports&task=jlxmlexport.display

The filename only contains date-time info (e.g. -150804-160330.jlg), whereas some prefix is expected.

**Comment by JKoelman** [comment]
hi Aad,  

was wondering what view you meant but did found out:  It's "Export Project" in the Project slider.
You're right there is indeed an error but  am convinced you will resolve it.

**Comment by JKoelman** [comment]
will close the issue as @aad4 fixed the issue
